# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on: push

jobs:
  test:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      # Each step has a name, some code, and some options
      - name: Check out the code
        uses: actions/checkout@v3 # This is a reference to some code to run

      # This step installs the Python version we want
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: | # Note that there's no reference here — just commands to run
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data
        run: node client.js
        # Environment variables used by the `client.js` script to create
        # a new PostgreSQL table.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: localhost
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
      
      # Now we run our tests
      - name: Test with pytest
        run: |
          pipenv run pytest